### ISSUE TITLE
How to refresh the api key ?

### ISSUE THREAD

**Issue by ahmedsliman** [madcoda/php-youtube-api#25]
I use an api key generated from google console but it expires every 24 hours, How can i make it valid for ever or for long time ?

Thanks

**Comment by jamesggordon** [comment]
If you have generated the correct key using the correct method, it should not have a 24 hour limit. There are some Google API keys that *do* have a 24 hour limit (eg. the Admin API), but to the best of my knowledge the YouTube API 3.0 should not have a time limit on the API key.

Try regenerating your key by logging into the Google Developers Console, clicking into your project and then clicking on the Credentials option under APIs. There should be a couple of options here, but the one you want is "Create new Key" under the "Public API Access" section. If that navigation sequence doesn't make sense then perhaps you haven't generated the right kind of key. (It would not surprise me if some API keys worked across multiple APIs).

I generated my key months ago using this method and it still works fine.

**Comment by madcoda** [comment]
The key should not expires every 24 hours, I'm closing this now.
