### ISSUE TITLE
Planning on making it able to Video Upload?

### ISSUE THREAD

**Issue by orliesaurus** [madcoda/php-youtube-api#30]
Just wondering if there are any plans to build something to enable the upload of videos with this wrapper?

**Comment by andrewcaulfield** [comment]
+1

**Comment by ghprod** [comment]
:+1:

**Comment by jaggedsoft** [comment]
There are already other libraries that do that:
https://github.com/tokland/youtube-upload (command line, made in python) (I use this one from PHP)
https://www.npmjs.com/package/youtube-uploader (above example, wrapped for use in nodejs)
https://github.com/grayleonard/node-youtube-resumable-upload (pure nodejs)

madcoda, good job making this library without oauth. Thanks!

**Comment by orliesaurus** [comment]
cool - that'll help others who are still looking for this! thanks for the links

**Comment by jubairsaidi** [comment]
Video upload is critical!  +1

In the mean time I'll have to fork and look at integrating video upload (I need it now).

**Comment by madcoda** [comment]
Currently I don't have the plan to add this feature, feel free to send pull requests!
