### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by lismansihotang** [madcoda/php-youtube-api#33]
Fatal error: Uncaught exception 'Exception' with message 'Curl Error : SSL certificate problem: unable to get local issuer certificate' in C:\xampp\htdocs\php-youtube-api-master\lib\Madcoda\Youtube.php:475 Stack trace: #0 C:\xampp\htdocs\php-youtube-api-master\lib\Madcoda\Youtube.php(75): Madcoda\Youtube->api_get('https://www.goo...', Array) #1 C:\xampp\htdocs\php-youtube-api-master\index.php(10): Madcoda\Youtube->getVideoInfo('rie-hPVJ7Sw') #2 {main} thrown in C:\xampp\htdocs\php-youtube-api-master\lib\Madcoda\Youtube.php on line 475

**Comment by lismansihotang** [comment]
Hi Macoda, can you help me?thx

**Comment by madcoda** [comment]
Hi lismansihotang, This has been asked a few times, please search the closed issues

https://github.com/madcoda/php-youtube-api/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+Curl

or this stackoverflow post
http://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok/16495053#16495053

**Comment by lismansihotang** [comment]
Hi Jason,

thx for help me. i will contact you again

On Mon, May 11, 2015 at 7:31 PM, Jason Leung <notifications@github.com>
wrote:

> Hi lismansihotang, This has been asked a few times, please search the
> closed issues
>
>
> https://github.com/madcoda/php-youtube-api/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+Curl
>
> or this stackoverflow post
>
> http://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok/16495053#16495053
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madcoda/php-youtube-api/issues/33#issuecomment-100891429>
> .
>



-- 
*Lisman Tua Sihotang*
Contact No. : +6285715736296
Web Programmer CBN Indonesia
Jl. Sriwijaya Kav. 5-7
Lippo Cikarang, Bekasi 17550

**Comment by madcoda** [comment]
You're welcome!

**Comment by rodrigopolo** [comment]
If you are using WampServer 2.5 you'll have to download this .pem file:
https://gist.github.com/VersatilityWerks/5719158/download

And edit this two PHP.INI files:
```
C:\wamp\bin\apache\Apachex.x.x\bin
C:\wamp\bin\php\phpx.x.xx
```
Sources:
http://stackoverflow.com/a/25706713/218418
http://flwebsites.biz/posts/how-fix-curl-error-60-ssl-issue
