### ISSUE TITLE
How can I get this to run in just PHP?

### ISSUE THREAD

**Issue by leecollings** [madcoda/php-youtube-api#35]
I can't figure out exactly how this is meant to be loaded in pure PHP. Which file in your ZIP needs to be included?

I'm assuming I can't use the `use Madcoda...` line as I get a fatal error.

Please give some easier tutorials to get started,.

**Comment by madcoda** [comment]
Using composer is the easiest, also better way to use this package

Getting started with composer
https://getcomposer.org/doc/00-intro.md

**Comment by Stichoza** [comment]
https://getcomposer.org/doc/00-intro.md
