### ISSUE TITLE
Not able to get any data

### ISSUE THREAD

**Issue by sachinwng** [madcoda/php-youtube-api#49]
I am not able fetch any information using any function

**Comment by madcoda** [comment]
What's your current setup? have you [obtain the API key from the Google API console](http://code.google.com/apis/console)?

And Please read the wiki on how to use this library with [PHP with composer](https://github.com/madcoda/php-youtube-api/wiki/started-with-php-composer), [Laravel 4](https://github.com/madcoda/php-youtube-api/wiki/started-with-laravel-4) and [Laravel 5](https://github.com/madcoda/php-youtube-api/wiki/started-with-laravel-5).
