### ISSUE TITLE
Laravel 5.3?

### ISSUE THREAD

**Issue by tecnosoftware** [madcoda/php-youtube-api#51]
I am doing the installation according to the documentation and it does not work

FatalThrowableError in YoutubeController.php line 11:
Class 'App\Http\Controllers\Youtube' not found;

help!

**Comment by madcoda** [comment]
Please read the [Getting started with Laravel 5 project](https://github.com/madcoda/php-youtube-api/wiki/started-with-laravel-5)

**Comment by bobbwal** [comment]
I getting this same error after following the guide, any ideas?
