### ISSUE TITLE
Class 'Madcoda\Youtube' not found

### ISSUE THREAD

**Issue by sixty8** [madcoda/php-youtube-api#56]
for laravel 5.3 in YoutubeServiceProviderLaravel5 line 33

**Comment by mahan66** [comment]
I have the same issue :-?

**Comment by mahan66** [comment]
I found the problem:

Line 5 in YoutubeServiceProviderLaravel5.php (use `Madcoda\Youtube;`) should be removed.

Please fix it. tx :-)

**Comment by Anahkiasen** [comment]
That's not the only issue though, `Madcoda\Youtube` doesn't exist, it's `Madcoda\Youtube\Youtube`.

**Comment by mahan66** [comment]
I think because `Madcoda\Youtube\Youtube` is in the namespace of `Madcoda\Youtube`, there is no need to use it at the top of `YoutubeServiceProviderlaravel5.php`.

**Comment by Anahkiasen** [comment]
No yeah but what I meant more is that the SP is currently binding to the container a class that doesn't exist so you can't really inject it anywhere. The facade will work and all but that's it.

**Comment by mahan66** [comment]
@Anahkiasen  Yeah. You are right :-)

**Comment by dmaicher** [comment]
I'm getting the same since upgrading to `1.2.2` but not using Laravel. Since this is a patch release I would consider this a BC break? :cry:

**Comment by iquito** [comment]
With version 1.2.2 I am getting "Class 'Madcoda\Youtube' not found" and "Class 'Illuminate\Support\Facades\Facade' not found" - with version 1.2.1 it works fine. I am using Symfony 3.2, so the requested Laravel class is surprising.

**Comment by madcoda** [comment]
Sorry guys, it's done now. Please install v1.2.3

**Comment by Anahkiasen** [comment]
@madcoda Yes and no, the class being bound to the container is still `Madcoda\Youtube` which prevents dependency injection

**Comment by madcoda** [comment]
@Anahkiasen Ok, I understand what you mean.
I have fixed this in master, could you help verify if it's working properly? (use "dev-master" version in composer.json )
Thanks.

**Comment by Anahkiasen** [comment]
Yup, all good!

**Comment by erikobox** [comment]
Are you kidding me? Where is the official youtube php sdk? What is this crap? Not working!! Madcoda\Youtube\Youtube not found !
