### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by abubakar-iqbal** [madcoda/php-youtube-api#74]
Hi, 
I faced this error today. please have a look.

Error 400 'invideo_promotion' : unexpectedPart

**Comment by CarlPiper** [comment]
I also have this

**Comment by tambait** [comment]
"invideoPromotion" part is deprecated in Channels. I have created [pull request](https://github.com/madcoda/php-youtube-api/pull/73) to fix the issue, but not sure if this project is maintained anymore (there are few PR from 2017)

**Comment by soif** [comment]
Confirmed: PR #73 fixes this bug!

Thanks @tambait 👍
